# Generated by Django 5.0.1 on 2026-01-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="mathpix_content",
            field=models.TextField(blank=True),
        ),
    ]
